general {
    hide_cursor = false
}

background {
    monitor =
    path = ~/Downloads/germoney/black.jpg
    blur_passes = 3
    blur_size = 10
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    font_size = 128
    font_family = Sans

    color = rgba(cdb4ffff)

    position = 0, -80
    halign = center
    valign = top
}

# Date (optional small line under time)
label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A, %d %B')"
    font_size = 24
    font_family = Sans

    color = rgba(ffffffaa)

    position = 0, -320
    halign = center
    valign = top
}

# Password input
input-field {
    monitor =

    size = 350, 70
    outline_thickness = 2

    outer_color = rgba(cdb4ffff)
    inner_color = rgba(0f0a14cc)
    font_color = rgba(ffffffff)

    #dots_color = rgba(cdb4ffff)
    dots_size = 0.25
    dots_spacing = 0.3

    fade_on_empty = false

    position = 0, -50
    halign = center
    valign = center
}

#MPRIS
label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/scripts/get_player.sh

    font_size = 18
    font_family = Sans
    color = rgba(ffffffcc)

    position = 0, 020
    halign = center
    valign = bottom
}